### ISSUE TITLE
Healthcheck is not working

### ISSUE THREAD

**Issue by Marfien** [Infumia/agones4j#110]
Hello there,

I was looking around for a java sdk for agones and yours is looking very promissing. I created an instance of Agones as described in the README with `private static final Agones agones = Agones.builder().withChannel().build();` and tried to put my gameserver into ready-state with `agones.ready()`. I implemented my healthcheck for reasons in my own scheduled thread as:
```java
var health = agones.healthCheckStream();
scheduleTask(this, () -> {
        this.logger.info("Sending health ping");
        health.onNext(Sdk.Empty.getDefaultInstance());
}).schedule(Duration.ofSeconds(5), Duration.ofSeconds(1));
```

The sidecar container dose not seem to get any response of the health ping nor the ready call. The GameServer is changing its state from Scheduled straight to Unhealthy.
Am I doing something wrong?

Greetings

**Comment by portlek** [comment]
Thank you for the report. That's odd because I'm using this library for my server and things are looking good for me. I'll create a simple example in the repo to reproduce it when I'm available.

**Comment by portlek** [comment]
Example folder has been added.
